### ISSUE TITLE
Problem with open_basedir on shared host

### ISSUE THREAD

**Issue by herrschuessler** [timber/timber#1261]
### Actual behavior
When testing my Timber-powered site on a shared hosting environment, I get the following error:

```
Warning: realpath(): Requested File(/) is outside allowed path(s) in /home2/www/SOME/PATHS/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 37

Warning: is_dir(): Requested File(/) is outside allowed path(s) in /home2/www/SOME/PATHS/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 102

Fatal error: Uncaught Twig_Error_Loader: The "/" directory does not exist ("/"). in /home2/www/SOME/PATHS/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:103
Stack trace:
#0 /home2/www/SOME/PATHS/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(84): Twig_Loader_Filesystem->addPath('/', '__main__')
#1 /home2/www/SOME/PATHS/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(42): Twig_Loader_Filesystem->setPaths(Array)
#2 /home2/www/SOME/PATHS/wp-content/plugins/timber-library/lib/Loader.php(132): Twig_Loader_Filesystem->__construct(Array, '/')
#3 /home2/www/SOME/PATHS/wp-content/plugins/timber-library/lib/Loader.php(142): Timber\Loader->get_loader()
#4 /home2/www/SOME/PATHS/wp-content/plugins/timber-library/lib/Loader.php(66): Timber\Loader->get_twig()
#5 /home2/www/SOME/PATHS/wp-content/plugins/timber-l in /home2/www/SOME/PATHS/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 103
```

The value of `ini_get('open_basedir')` on my host is an empty string.

Changing the function at Line 124 in lib/Loader.php
```php
public function get_loader() {
	$open_basedir = ini_get('open_basedir');
	$paths = array_merge($this->locations, array($open_basedir ? ABSPATH : '/'));
	$paths = apply_filters('timber/loader/paths', $paths);
	$rootPath = '/';
	if ( $open_basedir ) {
		$rootPath = null;
	}
	$fs = new \Twig_Loader_Filesystem($paths, $rootPath);
	$fs = apply_filters('timber/loader/loader', $fs);
	return $fs;
}
```
to
```php
public function get_loader() {
	$open_basedir = ini_get('open_basedir');
	$paths = array_merge($this->locations, array($open_basedir ? '/' : ABSPATH));
	$paths = apply_filters('timber/loader/paths', $paths);
	$rootPath = ABSPATH;
	if ( $open_basedir ) {
		$rootPath = null;
	}
	$fs = new \Twig_Loader_Filesystem($paths, $rootPath);
	$fs = apply_filters('timber/loader/loader', $fs);
	return $fs;
}
```
resolves the issue for me, but I'm not realy sure why - and if this would work in other environments.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.6.1, PHP 7.0.13, Timber 1.1.10

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress

**Comment by Luckyfella73** [comment]
I have the same issue on a shared host.

```
Fatal error: Uncaught Twig_Error_Loader: The "/" directory does not exist ("/"). in /var/www/web86/html/staging/www/content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:101
Stack trace:
#0 /var/www/web86/html/staging/www/content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(82): Twig_Loader_Filesystem->addPath('/', '__main__')
#1 /var/www/web86/html/staging/www/content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(40): Twig_Loader_Filesystem->setPaths(Array)
#2 /var/www/web86/html/staging/www/content/plugins/timber-library/lib/Loader.php(142): Twig_Loader_Filesystem->__construct(Array, '/')
#3 /var/www/web86/html/staging/www/content/plugins/timber-library/lib/Loader.php(102): Timber\Loader->get_loader()
#4 /var/www/web86/html/staging/www/content/plugins/timber-library/lib/Timber.php(294): Timber\Loader->choose_template(Array)
#5 /var/www/web86/html/staging/www/content/plugins/timber-library/lib/Timber.php(362): Timber\Timber::compile('templates/la in /var/www/web86/html/staging/www/content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 101
```

The way the @herrschuessler solved the problem didn't work for me. In my case I had to prevent array merging `array($open_basedir ? ABSPATH : '/')`

I replaced the original line:
`$paths = array_merge($this->locations, array($open_basedir ? ABSPATH : '/'));`

with:
`$paths = $this->locations;`

My environment:
PHP 7.0.15
WP: 4.8.1
Timber Twig: 1.4.1

**Comment by herrschuessler** [comment]
I can confirm that this issue still exists for me with Timber 1.5.2, but the solution proposed by @Luckyfella73 didn't resolve it for me, either.

**Comment by palmiak** [comment]
Are you still having problems with it?

**Comment by Luckyfella73** [comment]
@palmiak I only had that issue once so I guess it was related to _unusual server setup_. Asking me you could close this thread - we could reopen it in case it happens again. But @herrschuessler started this thread so better wait for his response :)

**Comment by herrschuessler** [comment]
Yes, my problem persists, but let's close this anyway as I, too, suspect _unusual server setup_.
