### ISSUE TITLE
WPML language_attributes function conflict

### ISSUE THREAD

**Issue by luism-s** [timber/timber#1371]
There seems to be a conflict between the newest (1.3.0) version of Timber and WPML. WPML defines a function named language_attributes(), and that seem to cause conflicts with Timber code. When I open the website, I get a fatal error (output bellow).
By commenting the lines timber/timber/lib/Site.php:183 and timber/timber/lib/Site.php:166 

Of course removing this code is not a solution, so there needs to be a workaround. Maybe renaming language_attributes to lang_attributes?

### Expected behavior

Expected to open the website I'm developing without any errors

### Actual behavior

`Fatal error: Uncaught LogicException: Function "language_attributes" is already registered. in Fatal error: Uncaught LogicException: Function "language_attributes" is already registered. in /var/www/myproject/wp-content/themes/myproject/vendor/twig/twig/lib/Twig/Extension/Staging.php:30 Stack trace: #0 /var/www/myproject/wp-content/themes/myproject/vendor/twig/twig/lib/Twig/ExtensionSet.php(162): Twig_Extension_Staging->addFunction(Object(Twig_SimpleFunction)) #1 /var/www/myproject/wp-content/themes/myproject/vendor/twig/twig/lib/Twig/Environment.php(807): Twig_ExtensionSet->addFunction(Object(Twig_SimpleFunction)) #2 /var/www/myproject/wp-content/themes/myproject/vendor/timber/timber/lib/FunctionWrapper.php(59): Twig_Environment->addFunction(Object(Twig_SimpleFunction)) #3 /var/www/myproject/wp-includes/class-wp-hook.php(298): Timber\FunctionWrapper->add_to_twig(Object(Twig_Environment)) #4 /var/www/myproject/wp-includes/plugin.php(203): WP_Hook->apply_filters(Object(Twig_Environment), Array) #5 /var/www/myproject/wp-content/themes/myproject/vendor/timber/timber/lib/Twig.php(207): apply_filters('timber/twig', Object(Twig_Environment)) #6 in /var/www/myproject/wp-content/themes/myproject/vendor/twig/twig/lib/Twig/Extension/Staging.php on line 30`

### Steps to reproduce behavior
* Install Timber v1.3.0
* Install Sitepress-Multilingual-CMS plugin (WPML)
* Watch chaos descend upon your website

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.3, PHP 7.0, Timber 1.3.0, Sitepress-Multilingual-CMS 3.6.3

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed Timber with Composer in my theme folder, and WPML plugin by placing the plugin folder in wp-content/plugins.

**Comment by roopemerikukka** [comment]
Yep I was able to reproduce this.

**Comment by jarednova** [comment]
Thanks @luism-s and @roopemerikukka — I'm working through this now. It's clear that there are a bunch of issues w the Timber 1.3 + PHP 7 + Twig 2.0 combo so I've renamed 1.3.0 to be 1.3.0 beta while we work this stuff out

**Comment by roopemerikukka** [comment]
I think this issue still exists in the new release of **1.3.0**.

**Comment by jarednova** [comment]
Thanks @roopemerikukka — I'll give this a deeper dive today/tonight

**Comment by jarednova** [comment]
@roopemerikukka @luism-s — Despite several attempts I wasn't able to see the error. Here were my steps:
- Install Timber 1.3.0 through Composer
- WP 4.7.3
- WPML v 3.6.3
- Create a post in native language, alternate in French. 

I looked at the regular post, the translation, the homepage — but no error. That said, I have an improvement to the code in #1410 that _may_ fix the issue. By converting the `language_attributes` property to a method on `Timber\Site` the global `language_attributes` method will execute later (on Twig compilation) this might resolve by executing later after WPML and WP have worked out the handling of that method.

Phewwwwwww ....

**Comment by luism-s** [comment]
@jarednova Thank you for your work. 
I will test this issue once again next monday and post the results in this thread.

**Comment by luism-s** [comment]
@jarednova I just tested. 1.3.0 is working fine now! Thank you

You may close this issue if you want
