### ISSUE TITLE
`mime_content_type` not supported in some PHP Installs

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1797]
I received an email bug report about v 1.8.0 and [the introduction of `mime_content_type`](https://github.com/timber/timber/compare/1.7.1...1.8.0) in `ImageHelper::is_svg`:

```
[21-Sep-2018 14:14:14 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mime_content_type() in /home/ruisenreuring/public_html/web/app/plugins/timber-library/lib/ImageHelper.php:154

Stack trace:
#0 /home/ruisenreuring/public_html/web/app/plugins/timber-library/lib/Image/Operation/Resize.php(176): Timber\ImageHelper::is_svg('/home/ruisenreu...')
#1 /home/ruisenreuring/public_html/web/app/plugins/timber-library/lib/ImageHelper.php(579): Timber\Image\Operation\Resize->run('/home/ruisenreu...', '/home/ruisenreu...')
#2 /home/ruisenreuring/public_html/web/app/plugins/timber-library/lib/ImageHelper.php(71): Timber\ImageHelper::_operate('https://www.rui...', Object(Timber\Image\Operation\Resize), false)
#3 /home/ruisenreuring/public_html/web/app/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(462) : eval()'d code(41): Timber\ImageHelper::resize('https://www.rui...', 58, 30, 'center')
#4 /home/ruisenreuring/public_html/web/app/plugins/timber-library/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_042318cf4d6b07fb3d85 in /home/ruisenreuring/public_html/web/app/plugins/timber-library/lib/ImageHelper.php on line 154
```

Apparently `mime_content_type` might require a PECL installation in certain PHP versions or explicitly enabling in `php.ini`:

https://stackoverflow.com/questions/14809054/mime-content-type-function-not-working

Given that this will be distributed to WP.org we should look for a method that's 100% compatible with supported PHP versions

**Comment by jarednova** [comment]
Closed by #1798
