### ISSUE TITLE
[BUG] timber 2x/git, new fatal php error:  "Call to a member function load() on bool"

### ISSUE THREAD

**Issue by pgnd** [timber/timber#2765]
after update to
```
composer show timber/timber
	name     : timber/timber
	descrip. : Plugin to write WordPress themes w Object-Oriented Code and the Twig Template Engine
	keywords : templating, themes, timber, twig
	versions : * 2.x-dev
	type     : library
	license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
	homepage : http://timber.upstatement.com
	source   : [git] https://github.com/timber/timber.git 9f37aa859b2e04de686f371510532af8f7d5e080
	dist     : [zip] https://api.github.com/repos/timber/timber/zipball/9f37aa859b2e04de686f371510532af8f7d5e080 9f37aa859b2e04de686f371510532af8f7d5e080
	path     : /srv/www/wp/vendor/timber/timber
	names    : timber/timber
	...
```

site access now fails with php fatal error
```
tail /var/log/nginx/php-fpm.log
	[08-Jun-2023 11:45:35 UTC] PHP Fatal error:  Uncaught Error: Call to a member function load() on bool in /srv/www/wp/vendor/timber/timber/src/Loader.php:176
	Stack trace:
	#0 /srv/www/wp/vendor/timber/timber/src/Timber.php(1445): Timber\Loader->render('index.twig', Array, false, 'default')
	#1 /srv/www/wp/vendor/timber/timber/src/Timber.php(1582): Timber\Timber::compile(Array, Array, false, 'default', true)
	#2 /srv/www/wp/web/app/themes/mytheme/index.php(11): Timber\Timber::render(Array, Array)
	#3 /srv/www/wp/web/wp/wp-includes/template-loader.php(106): include('/srv/www/w...')
	#4 /srv/www/wp/web/wp/wp-blog-header.php(19): require_once('/srv/www/w...')
	#5 /srv/www/wp/web/index.php(6): require('/srv/www/w...')
	#6 {main}
	  thrown in /srv/www/wp/vendor/timber/timber/src/Loader.php on line 176
```

where
```
cat index.php
	<?php
	
	$context = Timber::context();
	$templates = ['index.twig'];
	if (is_home()) {
	        array_unshift($templates, 'front-page.twig', 'home.twig');
	}
	Timber::render($templates, $context);
```

**Comment by gchtr** [comment]
The **index.php** looks fine to me so far.

It looks like the Twig instance was lost in the loader. Do you use any of the following filters?

- `timber/loader/twig`
- `twig_apply_filters`
- `timber/twig`
- `get_twig`

If yes, can you show us how you use them?

**Comment by pgnd** [comment]
@gchtr 

my setup's a simple child theme of timber_s
```
wp-cli theme list
	+---------------------+----------+--------+---------+
	| name                | status   | update | version |
	+---------------------+----------+--------+---------+
	| mytheme             | active   | none   | 1.0.0   |
	| timber_s            | parent   | none   |         |
	| twentytwentyone     | inactive | none   | 1.8     |
	| twentytwentythree   | inactive | none   | 1.1     |
	+---------------------+----------+--------+---------+
```

on site access, as above, fatal error,
```
tail -f /var/log/nginx/php-fpm.log <==
	[09-Jun-2023 09:05:09 UTC] PHP Fatal error:  Uncaught Error: Call to a member function load() on bool in /srv/www/wp/vendor/timber/timber/src/Loader.php:176
	Stack trace:
	#0 /srv/www/wp/vendor/timber/timber/src/Timber.php(1445): Timber\Loader->render('index.twig', Array, false, 'default')
	#1 /srv/www/wp/vendor/timber/timber/src/Timber.php(1582): Timber\Timber::compile(Array, Array, false, 'default', true)
	#2 /srv/www/wp/web/app/themes/mytheme/index.php(11): Timber\Timber::render(Array, Array)
	#3 /srv/www/wp/web/wp/wp-includes/template-loader.php(106): include('/srv/www/w...')
	#4 /srv/www/wp/web/wp/wp-blog-header.php(19): require_once('/srv/www/w...')
	#5 /srv/www/wp/web/index.php(6): require('/srv/www/w...')
	#6 {main}
	  thrown in /srv/www/wp/vendor/timber/timber/src/Loader.php on line 176
```

checking parent theme rev,
```
cd themes/timber_s
git log -n 1
      1 commit 1823e4d0da7e664a674c9c26fc16fa8a3ad069bd (HEAD -> 2.x-revert-theme-subfolder, origin/2.x-revert      1 -theme-subfolder)
      2 Author: Lukas Gaechter <lukas.gaechter@mind.ch>
      3 Date:   Tue Mar 14 07:36:18 2023 +0100
      4
      5     Revert moving template files into a theme subfolder
      6
      7     Having template files in a subfolder can lead to unexpected consequences, as we can see in https:/      7 /github.com/timber/timber/pull/2458. There may be other effects. Working around them is more tedious t      7 han the benefits a subfolder brings.
```

editing @ parent,
```
edit themes/timber_s/functions.php

	59	---	class StarterSite extends Timber\Site {
		+++	class xxStarterSite extends Timber\Site {

	159	---	new StarterSite();
		+++	//new StarterSite();

```

now, site-access is restored ... all good; no PHP error.

this wasn't an issue previously.
i'm digging to try to figure out what changed & when.

**Comment by gchtr** [comment]
In your `myStarterSite` class, you add the following filters:

```php
add_filter('timber/context', [$this, 'add_to_context']);
add_filter('timber/twig/filters', [$this, 'add_twig_filters']);
```

Can you show us the contents of the `myStarterSite::add_to_context()` and `myStarterSite::add_twig_filters()` methods?

**Comment by pgnd** [comment]
@gchtr 

> contents of the myStarterSite::add_to_context() and myStarterSite::add_twig_filters() methods?

```
...
    public function add_twig_filters($filters) {
        $filters['webpack_asset'] = [
            'callable' => [$this, 'get_manifest_asset_twig'],
        ];

        return $filters;
    }

   public function add_to_context($context) {
        $context['foo'] = 'bar';
        $context['stuff'] = 'I am a value set in your functions.php file';
        $context['notes'] = 'These values are available everytime you call Timber::context();';

        foreach (array_keys(get_registered_nav_menus()) as $location) {
            // Bail out if menu has no location.
            if (!has_nav_menu($location)) {
                continue;
            }

            $menu = Timber::get_menu($location);

            $context[$location] = $menu;
        }

        $context['site'] = $this;

        return $context;
    }
...
```

**Comment by pgnd** [comment]
@gchtr 

'needs-info' flag is still set here.

do u still need something? or just forgot to clear flag?

**Comment by Levdbas** [comment]
Hi @pgnd ,

Which version of the timber starter site are you using? The `StarterSite `  [class](https://github.com/timber/starter-theme/blob/2.x/theme/functions.php) might be outdated. The change in the v2 branch of the starter theme:

```php
-- $context['menu']  = new Timber\Menu();
++ $context['menu']  = Timber::get_menu();
```
