### ISSUE TITLE
[BUG] Fatal error: Uncaught Error: Typed property Timber\Post::$wp_object must not be accessed before initialization 

### ISSUE THREAD

**Issue by pratik-londhe4** [timber/timber#2921]
### Expected Behavior

Posts should display as usual

### Actual behavior

"2024-02-12T11:40:25.758338946Z","PHP message: Fatal error: Uncaught Error: Typed property Timber\Post::$wp_object must not be accessed before initialization in /var/www/wp-content/themes/mytheme/vendor/timber/timber/src/Post.php:298"

### Steps to reproduce behavior

This issue does not happen on local env but on deployment only, this is happening on some posts, other posts show as usual, I am working on finding why this is happening.

### What version of Timber are you using?

2

### What version of WordPress are you using?

6.3.3

### What version of PHP are you using?

8

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @pratik-londhe4 

Could you provide a little more context on what kind of query you are running and provide some example code? And is the development environment also running PHP 8.0?

**Comment by pratik-londhe4** [comment]
hi, @Levdbas 

this is the stacktrace of the error,

```
PHP message: PHP Fatal error: Uncaught Error: Typed property Timber\Post::$wp_object must not be accessed before initialization in /var/www/wp-content/themes/mytheme/vendor/timber/timber/src/Post.php:298
06:59:20 AM

Stack trace:
06:59:20 AM

#0 /var/www/wp-content/themes/mytheme/vendor/timber/timber/src/PostsIterator.php(49): Timber\Post->setup()
06:59:20 AM

#1 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Environment.php(360) : eval()'d code(57): Timber\PostsIterator->current()
06:59:20 AM

#2 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Template.php(394): __TwigTemplate_0f061f8719fb37ced083e2d53ebc093d->doDisplay(Array, Array)
06:59:20 AM

#3 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
06:59:20 AM

#4 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Environment.php(360) : eval()'d code(45): Twig\Template->display(Array)
06:59:20 AM

#5 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Template.php(394): __TwigTemplate_bb6296782196d8ce74d42c5e52320646->doDisplay(Array, Array)
06:59:20 AM

#6 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
06:59:20 AM

#7 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Environment.php(360) : eval()'d code(108): Twig\Template->display(Array)
06:59:20 AM

#8 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Template.php(171): __TwigTemplate_816c6fcb5accde8d292baa83fd36426c->block_page_body(Array, Array)
06:59:20 AM

#9 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Environment.php(360) : eval()'d code(346): Twig\Template->displayBlock('page_body', Array, Array)
06:59:20 AM

#10 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Template.php(394): __TwigTemplate_ad80f468514097a20879573fd3421ff2->doDisplay(Array, Array)
06:59:20 AM

#11 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
06:59:20 AM

#12 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
06:59:20 AM

#13 /var/www/wp-content/themes/mytheme/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
06:59:20 AM

#14 /var/www/wp-content/themes/mytheme/vendor/timber/timber/src/Loader.php(178): Twig\TemplateWrapper->render(Array)
06:59:20 AM

#15 /var/www/wp-content/themes/mytheme/vendor/timber/timber/src/Timber.php(1442): Timber\Loader->render('pages/single-co...', Array, false, 'default')
06:59:20 AM

#16 /var/www/wp-content/themes/mytheme/vendor/timber/timber/src/Timber.php(1579): Timber\Timber::compile('pages/single-co...', Array, false, 'default', true)
06:59:20 AM

#17 /var/www/wp-content/themes/mytheme/author.php(30): Timber\Timber::render('pages/single-co...', Array)
06:59:20 AM

#18 /var/www/wp-includes/template-loader.php(106): include('/var/www/wp-con...')
06:59:20 AM

#19 /var/www/wp-blog-header.php(19): require_once('/var/www/wp-inc...')
06:59:20 AM

#20 /var/www/index.php(17): require('/var/www/wp-blo...')
06:59:20 AM

#21 {main}
```

Yes both environments use PHP 8.

**Comment by Levdbas** [comment]
Hi @pratik-londhe4 ,

Sorry, but we cannot handle your ticket on just this information. I will gladly reopen your ticket when:

- You narrowed down on which posts this exactly occurs
- how the query on your author page looks like
- how you loop over the posts in the linked twig file 

This is not to be rude, but I hope you understand we need a little more to actually help you or see if this is an actual bug.

**Comment by pratik-londhe4** [comment]
hi, @Levdbas , no problem, I am sorry this issue was opened in rush, give me some time to investigate more and get more info on this so I can provide you with more context and the code.
Thank You!
