### ISSUE TITLE
[BUG] get_posts causes critical error when ACF relationship field contains deleted post ID

### ISSUE THREAD

**Issue by cbirdsong** [timber/timber#2935]
### Expected Behavior

Using `get_posts` on the field values would successfully return all the posts in the field that exist.

### Actual behavior

You get a critical error: `PHP Fatal error:  Uncaught Error: Call to a member function setup() on null in /wp-content/themes/tp/vendor/timber/timber/src/PostsIterator.php:49`

<details>
<summary>Full trace</summary>

```
PHP Fatal error:  Uncaught Error: Call to a member function setup() on null in /wp-content/themes/tp/vendor/timber/timber/src/PostsIterator.php:49
Stack trace:
#0 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(209): Timber\PostsIterator->current()
#1 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(171): __TwigTemplate_2f9003f5823cb0ea499bd9201063e7f0->block_content(Array, Array)
#2 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(117): Twig\Template->displayBlock('content', Array, Array)
#3 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4b1027f1807eeb1bcf28f466811755f4->block_container(Array, Array)
#4 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(103): Twig\Template->displayBlock('container', Array, Array)
#5 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4b1027f1807eeb1bcf28f466811755f4->block_wrapper(Array, Array)
#6 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(85): Twig\Template->displayBlock('wrapper', Array, Array)
#7 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4b1027f1807eeb1bcf28f466811755f4->doDisplay(Array, Array)
#8 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(99): Twig\Template->display(Array, Array)
#10 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(394): __TwigTemplate_2f9003f5823cb0ea499bd9201063e7f0->doDisplay(Array, Array)
#11 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#13 /wp-content/themes/tp/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#14 /wp-content/themes/tp/vendor/timber/timber/src/Loader.php(178): Twig\TemplateWrapper->render(Array)
#15 /wp-content/themes/tp/vendor/timber/timber/src/Timber.php(1442): Timber\Loader->render('/cpt-listi...', Array, false, 'default')
#16 /wp-content/themes/tp/vendor/timber/timber/src/Timber.php(1579): Timber\Timber::compile('/cpt-listi...', Array, false, 'default', true)
#17 /wp-content/themes/tp/_blocks/cpt-listing/cpt-listing.php(162): Timber\Timber::render('/cpt-listi...', Array)
#18 /wp-content/plugins/advanced-custom-fields-pro/pro/blocks.php(650): CPTListing\render_block(Array, '\n\n<p></p>\n\n', false, 590, Object(WP_Block), Array)
#19 /wp-content/plugins/advanced-custom-fields-pro/pro/blocks.php(571): acf_render_block(Array, '\n\n<p></p>\n\n', false, 590, Object(WP_Block), Array)
#20 /wp-content/plugins/advanced-custom-fields-pro/pro/blocks.php(504): acf_rendered_block(Array, '\n\n<p></p>\n\n', false, 590, Object(WP_Block))
#21 /wp-includes/class-wp-block.php(258): acf_render_block_callback(Array, '\n\n<p></p>\n\n', Object(WP_Block))
#22 /wp-includes/class-wp-block.php(244): WP_Block->render()
#23 /wp-includes/blocks.php(1484): WP_Block->render()
#24 /wp-includes/blocks.php(1522): render_block(Array)
#25 /wp-includes/class-wp-hook.php(324): do_blocks('<!-- wp:acf/her...')
#26 /wp-includes/plugin.php(205): WP_Hook->apply_filters('<!-- wp:acf/her...', Array)
#27 /wp-content/themes/tp/vendor/timber/timber/src/Post.php(1230): apply_filters('the_content', '<!-- wp:acf/her...')
#28 /wp-content/themes/tp/vendor/twig/twig/src/Extension/CoreExtension.php(1637): Timber\Post->content()
#29 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(51): twig_get_attribute(Object(Twig\Environment), Object(Twig\Source), Object(ThemePost), 'content', Array, 'any', false, false, false, 4)
#30 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4742378aeb3aa35327ba19a862cc001c->block_content(Array, Array)
#31 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(276): Twig\Template->displayBlock('content', Array, Array)
#32 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4aa7ce586e8d304cb61c4d7c0d5ba663->block_content_wrapper(Array, Array)
#33 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(176): Twig\Template->displayBlock('content_wrapper', Array, Array)
#34 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4aa7ce586e8d304cb61c4d7c0d5ba663->block_main_wrapper(Array, Array)
#35 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(118): Twig\Template->displayBlock('main_wrapper', Array, Array)
#36 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4aa7ce586e8d304cb61c4d7c0d5ba663->block_body_wrapper(Array, Array)
#37 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(74): Twig\Template->displayBlock('body_wrapper', Array, Array)
#38 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4aa7ce586e8d304cb61c4d7c0d5ba663->doDisplay(Array, Array)
#39 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#40 /wp-content/themes/tp/vendor/twig/twig/src/Environment.php(361) : eval()'d code(42): Twig\Template->display(Array, Array)
#41 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4742378aeb3aa35327ba19a862cc001c->doDisplay(Array, Array)
#42 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#43 /wp-content/themes/tp/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#44 /wp-content/themes/tp/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#45 /wp-content/themes/tp/vendor/timber/timber/src/Loader.php(178): Twig\TemplateWrapper->render(Array)
#46 /wp-content/themes/tp/vendor/timber/timber/src/Timber.php(1442): Timber\Loader->render('single.twig', Array, false, 'default')
#47 /wp-content/themes/tp/vendor/timber/timber/src/Timber.php(1579): Timber\Timber::compile(Array, Array, false, 'default', true)
#48 /wp-content/themes/tp/singular.php(16): Timber\Timber::render(Array, Array)
#49 /wp-includes/template-loader.php(106): include('/Users/coryb/Si...')
#50 /wp-blog-header.php(19): require_once('/Users/coryb/Si...')
#51 /index.php(17): require('/Users/coryb/Si...')
```
_(Lightly edited to remove personal/client-related info)_

</details>

### Steps to reproduce behavior

1. Create an ACF relationship field and add some posts to it.
2. Use `{{ get_posts(post.meta("relationship_field")) }}`.
3. View the page and see it work.
4. Delete one of the posts.
5. Try to view the page again and see a big ugly error.

### Notes

I haven't found any official documentation about it, but various discussions indicate that ACF's `get_field` function checks to see if posts in a relationship field exist before doing anything with the IDs: https://wordpress.org/support/topic/relationship-not-updated-on-delete/

I did not have time to check and see if this also happens if you use `get_posts` in PHP instead of Twig, nor did I have time to check if similar relational ACF field types like Post Object or Page Link have the same issue.

### What version of Timber are you using?

Timber 2.0

### What version of WordPress are you using?

Wordpress 6.4

### What version of PHP are you using?

PHP 8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @cbirdsong this bug was reported earlier and should be fixed by https://github.com/timber/timber/pull/2918 that will ship with Timber 2.1 soon™
